### ISSUE TITLE
Karta

### ISSUE THREAD

**Issue by SA6JKK** [ETAChalmers/ETA-Hemsida-3.0#7]
Kartan borde ha samma bredd som texten. Oändligt bred karta suger på desktop enligt mig.

**Comment by almbr** [comment]
Typ så att kartan är lika stor som den svarta ramen? På desktop d.v.s. På mobil får den expandera helt.

![eta_karta_skiss](https://user-images.githubusercontent.com/20804017/53376891-3a57ff80-3960-11e9-9244-76126a591b51.png)

**Comment by SA6JKK** [comment]
Ja typ så. Texten är väl begränsad i sidled så då tyckte jag att det skulle
passa att begränsa bredden på kartan med.

Den tis 26 feb. 2019 kl 00:47 skrev Erik Almbratt <notifications@github.com

**Comment by almbr** [comment]
Merge:at med master nu. @KonstigSak Vad sägs?

**Comment by SA6JKK** [comment]
Jag gillar det! Mycket bättre än innan, Det ger en mer enhetlig bild av hemsidan
